name: Flutter Workflow
env:
  FLUTTER_VERSION: "stable"
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Flutter
        uses: britannio/action-install-flutter@v1.0
        with:
          version: $FLUTTER_VERSION
      - name: Installing dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk
